# Generated by the release pipeline (update-tap). Manual edits are overwritten.
cask "emprise-desktop" do
  version "0.9.7"
  sha256 "3a9598458e685dadb5e081edbe4634cb9a9402c3b521cc6c4fc75a28c10466bb"

  url "https://github.com/senzalldev/emprise-app/releases/download/#{version}/emprise-desktop-macos.dmg"
  name "Emprise Desktop"
  desc "Desktop app for emprise — AI partner on your terms"
  homepage "https://emprise.dev"

  # The app ships an in-app auto-updater; tell brew so it doesn't
  # fight the self-update or flag a version drift.
  auto_updates true

  app "Emprise Desktop.app"
end
