# Generated by the release pipeline (update-tap). Manual edits are overwritten.
cask "emprise-desktop" do
  version "0.9.10"
  sha256 "f6d57393ec76c94fe7538e0188dc99bf6b5d4b5fdbac6c694d8b10eae427ab09"

  url "https://github.com/senzalldev/emprise-app/releases/download/#{version}/emprise-desktop-macos.dmg"
  name "Emprise Desktop"
  desc "Desktop app for emprise — AI partner on your terms"
  homepage "https://emprise.dev"

  # The app ships an in-app auto-updater; tell brew so it doesn't
  # fight the self-update or flag a version drift.
  auto_updates true

  app "Emprise Desktop.app"
end
