# Generated by the release pipeline (update-tap). Manual edits are overwritten.
cask "emprise-desktop" do
  version "0.9.2"
  sha256 "adfd2ded73b52ddb12129ec5aadfd58638d08206fb9ba0cbd672c00e6292aa73"

  url "https://github.com/senzalldev/emprise-app/releases/download/#{version}/emprise-desktop-macos.dmg"
  name "Emprise Desktop"
  desc "Desktop app for emprise — AI partner on your terms"
  homepage "https://emprise.dev"

  # The app ships an in-app auto-updater; tell brew so it doesn't
  # fight the self-update or flag a version drift.
  auto_updates true

  app "Emprise Desktop.app"
end
