# Generated by the release pipeline (update-tap). Manual edits are overwritten.
cask "pouncesql" do
  version "0.1.0"
  sha256 "107bc47f9280e24cc2d36a5177b9071fe82a29e36673feef349953ecb3c80ee5"

  url "https://github.com/senzalldev/pouncesql/releases/download/v\#{version}/PounceSQL-\#{version}.dmg"
  name "PounceSQL"
  desc "Native Azure SQL client for macOS with AI assistant and MCP server"
  homepage "https://github.com/senzalldev/pouncesql"

  auto_updates false

  depends_on macos: ">= :ventura"

  app "PounceSQL.app"

  caveats <<~EOS
    Before launching PounceSQL, run `az login` in a terminal to authenticate with Azure.
  EOS

  zap trash: [
    "~/Library/Application Support/PounceSQL",
    "~/Library/Preferences/dev.senzall.pouncesql.plist",
  ]
end
