# typed: false
# frozen_string_literal: true

# emprise — AI partner for your terminal. https://emprise.dev
# Generated by the release pipeline (update-tap). Manual edits are overwritten.
class Emprise < Formula
  desc "AI partner for your terminal — any model, your machine, your data"
  homepage "https://emprise.dev"
  version "0.9.5"

  on_macos do
    on_arm do
      url "https://github.com/senzalldev/emprise-app/releases/download/0.9.5/emprise-darwin-arm64"
      sha256 "2ac4488d4eaa38899ed628b7361812c386b2032425082109edbd75cffcdfe099"
    end
    on_intel do
      url "https://github.com/senzalldev/emprise-app/releases/download/0.9.5/emprise-darwin-amd64"
      sha256 "1898af5857b5687ce2e3f103393f25707e7428d621816ed2537e357d4521dfd4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/senzalldev/emprise-app/releases/download/0.9.5/emprise-linux-amd64"
      sha256 "b831ec7541d69cf6b84b315bbe7f1bfee9af849bc5d40ac9592128a17e71f3a6"
    end
    on_arm do
      url "https://github.com/senzalldev/emprise-app/releases/download/0.9.5/emprise-linux-arm64"
      sha256 "950723b1595274471b9e407c8fa40af08ad4e29c34e6504ad14495b236f4d7c1"
    end
  end

  def install
    binary = Dir["emprise-*"].first
    bin.install binary => "emprise"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/emprise --version")
  end
end
