# typed: false
# frozen_string_literal: true

# emprise — AI partner for your terminal. https://emprise.dev
# Generated by the release pipeline (update-tap). Manual edits are overwritten.
class Emprise < Formula
  desc "AI partner for your terminal — any model, your machine, your data"
  homepage "https://emprise.dev"
  version "0.9.3"

  on_macos do
    on_arm do
      url "https://github.com/senzalldev/emprise-app/releases/download/0.9.3/emprise-darwin-arm64"
      sha256 "54f555ee9610569830af4055be72cf0d7ec35da67c528b26d7172084915f1b25"
    end
    on_intel do
      url "https://github.com/senzalldev/emprise-app/releases/download/0.9.3/emprise-darwin-amd64"
      sha256 "ebff72fc8a3b0ab2df9c9d40cd87e813ddc00bb9e58df1f51fdff612991e4e43"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/senzalldev/emprise-app/releases/download/0.9.3/emprise-linux-amd64"
      sha256 "64861a3a9fdb1ad5a244fc8c3c496a11f66364c40ffe15a8de8ef7867f139b39"
    end
    on_arm do
      url "https://github.com/senzalldev/emprise-app/releases/download/0.9.3/emprise-linux-arm64"
      sha256 "a737564d034d61adfbcd922b3408266a5b3fa1f02d52cd399f20756c0bebfaf3"
    end
  end

  def install
    binary = Dir["emprise-*"].first
    bin.install binary => "emprise"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/emprise --version")
  end
end
