# typed: false
# frozen_string_literal: true

# emprise — AI partner for your terminal. https://emprise.dev
# Generated by the release pipeline (update-tap). Manual edits are overwritten.
class Emprise < Formula
  desc "AI partner for your terminal — any model, your machine, your data"
  homepage "https://emprise.dev"
  version "0.9.6"

  on_macos do
    on_arm do
      url "https://github.com/senzalldev/emprise-app/releases/download/0.9.6/emprise-darwin-arm64"
      sha256 "bdffb10b37ce4d23754d22fb1f67b6bc05fab43b56ae6f6ab31a96538f6691a2"
    end
    on_intel do
      url "https://github.com/senzalldev/emprise-app/releases/download/0.9.6/emprise-darwin-amd64"
      sha256 "b3e8dcdcd18004dad9da0ce64e731c796529b1a9aa736e6784fa23282be7638a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/senzalldev/emprise-app/releases/download/0.9.6/emprise-linux-amd64"
      sha256 "84254242bb26e65b642481cb1eaf1fc26fec4a72ca09ba38a441873a27c580d3"
    end
    on_arm do
      url "https://github.com/senzalldev/emprise-app/releases/download/0.9.6/emprise-linux-arm64"
      sha256 "0f8e71f6f8c4dec7c1887e1035a77db8178938cb81b5cd9929e5045e453c319e"
    end
  end

  def install
    binary = Dir["emprise-*"].first
    bin.install binary => "emprise"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/emprise --version")
  end
end
